version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: bookmyshow_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookmyshow
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d bookmyshow"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookmyshow_api
    restart: always
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://admin:password123@postgres_db:5432/bookmyshow?schema=public
      PORT: 3000
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  postgres_data:
